stages:
  - prepare
  - copy
  - prepare_env
  - install
  - build
  - run

prepare:
  stage: prepare
  script:
    - rm -rf /var/www/strapi/.env
  only:
    - main

copy_strapi:
  stage: copy
  script:
    - cp -R * /var/www/strapi/
  only:
    - main

prepare_env:
  stage: prepare_env
  script:
    - cd /var/www/strapi
    - chmod +x ./setup_env.sh
    - ./setup_env.sh
  only:
    - main

install_deps:
  stage: install
  before_script:
    - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash
    - sudo apt-get install -y nodejs
  script:
      - cd /var/www/strapi
      - npm install
  only:
      - main

build_strapi:
  stage: build
  before_script:
    - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash
    - sudo apt-get install -y nodejs
  script:
    - cd /var/www/strapi
    - npm install
    - npm run build
  only:
    - main

run_strapi:
  stage: run
  script:
      - cd /var/www/strapi
      - sudo systemctl restart elixir-strapi.service
  only:
      - main
