stages:
  - build
  - deploy

build_strapi:
  stage: build
  before_script:
    - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash
    - sudo apt-get install -y nodejs
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 hour
  only:
    - main

deploy_strapi:
  stage: deploy
  before_script:
    - rm -rf /var/www/strapi/*
  script:
    - mkdir -p /var/www/strapi
    - cp -R build/* /var/www/strapi/
    - sudo systemctl restart elixir-strapi.service
    - sudo systemctl restart nginx
  only:
    - main
