#!/bin/bash

echo HOST=$HOST >> .env
echo PORT=$PORT >> .env
echo APP_KEYS=$APP_KEYS >> .env
echo API_TOKEN_SALT=$API_TOKEN_SALT >> .env
echo ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET >> .env
echo TRANSFER_TOKEN_SALT=$TRANSFER_TOKEN_SALT >> .env
echo DATABASE_HOST=$DATABASE_HOST >> .env
echo DATABASE_PORT=$DATABASE_PORT >> .env
echo DATABASE_NAME=$DATABASE_NAME >> .env
echo DATABASE_USERNAME=$DATABASE_USERNAME >> .env
echo DATABASE_PASSWORD=$DATABASE_PASSWORD >> .env
echo JWT_SECRET=$JWT_SECRET >> .env
