/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import minecraftVersions from "../../src/plugins/minecraft-versions/strapi-admin";
import bundleRegistry from "../../src/plugins/bundle-registry/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
    "minecraft-versions": minecraftVersions,
    "bundle-registry": bundleRegistry,
  },
});
